set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-sensible' # optional recommended
set -g @plugin 'erikw/tmux-powerline'
# set -g @plugin 'egel/tmux-gruvbox'  # disabled - conflicts with tmux-powerline

# set -g @tmux-gruvbox 'dark'
set -g clock-mode-style 24
set -g mouse on

run "~/.tmux/plugins/tpm/tpm"
