[env]
GOBIN = "{{env.HOME}}/.local/bin"
OPENCODE_DISABLE_FFF=1

[bootstrap.hooks.pre-packages]
run = [
  "mise-ensure-repo remi",
  "mise-ensure-repo remi-module:remi-8.2",
  "mise-ensure-repo terra",
]

[bootstrap.packages]
"dnf:composer" = "latest"
"dnf:php" = "latest"
"dnf:php-cli" = "latest"
"dnf:php-fpm" = "latest"
"dnf:php-mbstring" = "latest"
"dnf:php-xml" = "latest"
"dnf:php-mysqlnd" = "latest"
"dnf:php-pgsql" = "latest"
"dnf:php-gd" = "latest"
"dnf:php-bcmath" = "latest"
"dnf:php-pecl-zip" = "latest"
"dnf:php-opcache" = "latest"
"dnf:nginx" = "latest"

[tools]
flutter = "latest"
go      = "latest"
gradle = "latest"
node   = "latest"
opencode = "latest"
pnpm   = "latest"
yarn   = "latest"
usage  = "latest"
uv     = "latest"

# Github backend
"github:phpactor/phpactor" = "latest"

# Go backend
"go:golang.org/x/tools/gopls" = "latest"

# npm packages
"npm:@mistweaverco/kulala-ls"   = "latest"
"npm:@mistweaverco/kulala-fmt"  = "latest"
"npm:@nestjs/cli"               = "latest"
"npm:prettier"                  = "latest"
"npm:httpyac"                   = "latest"
"npm:eas-cli"                   = "latest"

[settings]
experimental = true
node.corepack = true
npm.package_manager = "npm"
