[tools]
gradle = "latest"
node   = "latest"
pnpm   = "latest"
yarn   = "latest"
pi     = "latest"
usage  = "latest"
uv     = "latest"

# npm packages
"npm:@kilocode/cli"             = "latest"
"npm:@mistweaverco/kulala-ls"   = "latest"
"npm:@mistweaverco/kulala-fmt"  = "latest"
"npm:@nestjs/cli"               = "latest"
"npm:@qwen-code/qwen-code"      = "latest"
"npm:prettier"                  = "latest"
"npm:httpyac"                   = "latest"
"npm:eas-cli"                   = "latest"
"npm:pi-acp"                    = "latest"
"npm:opencode-ai"               = "latest"
"npm:tree-sitter-cli"           = "latest"

[settings]
experimental = true
node.corepack = true
npm.package_manager = "npm"
